language: node_js

node_js:
  - "node"   # Latest stable Node.js release
  - "lts/*"  # Latest LTS Node.js release

matrix:
  fast_finish: true

install:
  - yarn install

script:
  - echo -e "$(curl --silent https://raw.githubusercontent.com/FantasticFiasco/logo/master/logo.ansi)"
  - yarn workspaces run build
  - if [ "$TRAVIS_NODE_VERSION" == "node" ]; then yarn workspaces run coverage; fi
  - if [ "$TRAVIS_NODE_VERSION" != "node" ]; then yarn workspaces run test; fi
  - yarn workspaces run lint
  - echo temp
