language: node_js

os:
  - linux
  - osx

node_js:
  - "node"   # Latest stable Node.js release
  - "lts/*"  # Latest LTS Node.js release

matrix:
  fast_finish: true

install:
  - yarn install

script:
  - echo -e "$(curl --silent https://raw.githubusercontent.com/FantasticFiasco/logo/master/logo.ansi)"
  - yarn workspaces run build
  - yarn workspaces run test
  - yarn workspaces run lint
  - yarn release
