language: node_js

os:
  - linux
  - osx

node_js:
  - lts/*  # Latest LTS Node.js release
  - node   # Latest stable Node.js release

matrix:
  fast_finish: true

env:
  global:
    # Encrypted variable GITHUB_TOKEN
    secure: e3HkMirnP+Vy1thchzdx0qEB67YZWJFwjZSiUSIr+YhalaVfcFF2jSqkoWDc5DRFIeWmiaYnscaPS8FN4lAFs23EKqDO/H6lOmGxxVIrZMhGtMMTLz7aFcGXfsxorm7pdvQxBlGmc8MQZDnatRKtTJfFpc0ARU3CAhqkjm03varlKkaNpkLOK0bgBNT9MgElD+TJZ/wCjwf1A27lb97adfcjzZSQsNcnN63xj05gvh+RRrKmLJM7wjOFNSr1WMRksHIPrIq+CYKZdwIE1ibDhknzu5uuzLkg+7cjmAzGXWcMfOH3VpmwSZawUF77uMM9OH4G6Qwh4llAcjwT9lBo1LJu8cEw/EoqYQ7U8kd6OViWX7byX+08yi7W/sfcRXWuR717F4Vl7C5NIdGL3K/mZHvey2QGwgSSVOe5s+MBXYzd/NyjfNGhbPYlDL/viA3KVi86g8unzRnyrmpEYDuxinSWvWB4+o2gqsiqDfCPJENW8DEpIHhBcuU4kvbEqh4xyda3q0KaQFAixzdm73Nv36PH+cuYgXayXDwd6X4QDhqUN98FXn+O7mHnpP64wEeWak2vkpTHFvnkpRmKpmWuQJU+YD/VcaXW1pMeygKzw4L2spuvuUsCcA9u31oDTl3p8D+7VookJ6HfiuQjSoIwGTGG/BJV7Wf3BCln6hhxztA=
    # Encrypted variable NPM_TOKEN
    # secure: KnWprk8JXylXy+OGYMMXA+StM8rpgBhyj6O9/JL7xjrEQJkbhSLtx+VUxIg17dD2nP/mJjlmCRJXPCKwbSqqxYhLvy6rafv1iFG63Nt/RzHW+4BtNC1xLOKuj5FHBp7/gyDh79Lbnsf8oPhHZfPcPCi1JrLZ41QG3RIgayH7RkxWoNINoRSFL3eEzzcmjJbKz4fbx7EhJDPEUKlehky5z+BT9VThaFT6QJM/mGN2ZK8JHX1YZSqPaSIqPxNd7wTIiaracAStW3GhX6sTImTLcAEwe47b2tQuwQsYsm0E7Dh3fitieemqReOz5/bQR3MiXwd8G5GhWZPBsd6LlTd9kEsDrxdYZ9tBtLBxfJyAc2FIhSz5b6Fh4nAv7NdORVb4agDERwdeS1NmkZViRrjm3D1C6GddCVMylwOR+XTdMvZ4jPb+sDXTB3O4hc0ddGwLXqyJea02FvGCgzM2plmE4ZDBifUFu15A4+deTnAoPkW+UYe6023yKn4cLZQdXZCZSiLbwKkHKqZAg67okgebMvPGCq2Z4MzqQjG2h5n/ORJ9YuBo8eVEkw1Q4LGBVGzAElZ1JQuJ17yuJNOtEesXrX5XmZOrlzy+2EiHwwhZpZSOYEojxyPPGcICKt6daTPygHPGmkHfAyEsPqk+gRjePpG5rRpoCDH84rEME15wlTA=

install:
  - yarn install

script:
  - node ./scripts/temp.js
  - echo -e "$(curl --silent https://raw.githubusercontent.com/FantasticFiasco/logo/master/logo.ansi)"
  - yarn workspaces run build
  - yarn workspaces run test
  - yarn workspaces run lint
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$TRAVIS_NODE_VERSION" == "lts/*" ]; then node ./scripts/publish-on-tag.js; fi
