language: node_js

node_js:
  - "node"   # Latest stable Node.js release
  - "lts/*"  # Latest LTS Node.js release

matrix:
  fast_finish: true

install:
  - yarn install

script:
  - echo -e "$(curl --silent https://raw.githubusercontent.com/FantasticFiasco/logo/master/logo.ansi)"
  - if [ "$TRAVIS_NODE_VERSION" == "node" ]; then yarn coverage; fi
  - if [ "$TRAVIS_NODE_VERSION" != "node" ]; then yarn test; fi
  - yarn lint

deploy:
  - provider: npm
    email: mattias.kindborg@gmail.com
    api_key:
      secure: TSrS97/RsODjpKVej5GDhmKtjAtp7S6mUf71kmu5618E84FBioo3NqW1QQvOUxOzXCbsjqQJCBDDEdB8SB600/Mm+YZHcs+E+YmvQKDTbEuGf7Zn8ON7ktFmJAK/yfe4Y5lsOaqAwMu2mdL45lS2xUY2EMvdYuupO6ZJ6KZq0mus8q36/4rauLeZmcn796Mg05FJGAAAB1LYECuwIqQhi0FBdodtqaQwZiyKDM6BWTf01BvC3qMpcLmjxZz1EIVDR3Cjj25F0x7V1Kl5TXP+XTIvy6lPcrgUjy7n7V3Sd+BPlG+mZAL0SEhJAvOIpf8oa2PFwdlHGRM5dUV0K8xHnJq92mF2LigBVcjF3/pwNr0362FYQxXe5FFkXLVQjfsegLEJVmehVGzQ0oFZ1vqYyEuq2x0PAAdo+0jeuAMLt01P1ZVotHQMh/r79ipmBp1iGeHfbpyHNNa7iTF78HqEpfDU0DgNNssvGyO/6Thr535EaXHeZdyYBoOxL39eZurhT0uCiRiL6Shk6CRaEE7nDzkRifXR1v1p0ipYJpiu5/7KzWQGALpY2/LqqwDkzwfjc2Ofhi0+vr5jacTnmOkUbXr+OIIG6+Y8vJiLZ1MnywS+taN9vp2+TxN8w1N0QUCU+c45DWko0OpOQL/IkT7HqiPCKa/WoPyyOKMYa+lkdcM=
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    name: Release $TRAVIS_TAG
    api_key:
      secure: DdtLucoEnfaQOaePdruxtGfbYsm5G7jsjbngOfVPttcwdq/ybJ2FRfNhsqNb/VzizNbeD1Kp1uFcjXngcfGYQ9rXxeRHK01WnEtmlYekdWERTEWGuRcoWAhvQPuVvgG/qYK2aNdutAURMYXOTdVTP0Ix3OawhESqYpgIbzM7YdoUVZXOEOhvWyGlxLHcX1DLSQRarOmzbpPV71czMeagWLeTbtbs0kNorDWbK+w6MZHNEykqvsM1SuvoUU6GyCQ2SabZWrldnP2MA3d2pR1UtVk4G6CLyPJ62q94mhm87meynfTEvgEIChIwHiQRLLEt7F2kqAoZChrgyoVpCIuiUF1bSrHOYeJYfW7QH6H9yzuUqa5YVbf9g/Ztustte06jwnfyd4PgRppJczK+kQOSygbqvnzEwe2zyMFV/rVBb4VyZHeYgTW8ICe2a6eAVvz8Hfpww5t1Qtu3ETw7x2wyK87MzAH1fgZsZ71SQP+nygrfW7RimzyFZO5dsTgdSX1c7HFbIK6K/KCkSQ2nW54fuYGfqVfW4SXg9475hoLGjVVc7S4X8h4usXdsQxy8ILidYRIZkLPsJ/19wWoGO+6ZXdswsf9zINTGp5ymXReswvPy6CBv8wZZa2rmtpLk/nqF2uqF9455tU6md9PVQQIEpVugDgDcmL3W3zanN/Ilr4Q=
    on:
      tags: true
