name: axis-configuration

on:
  push:
    paths:
      - ".github/workflows/axis-configuration.yml"
      - "packages/axis-configuration/**"
    tags:
      - axis-configuration@**
  workflow_dispatch:

defaults:
  run:
    working-directory: "packages/axis-configuration"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 17.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: true
    - run: echo -e "$(curl --silent https://raw.githubusercontent.com/FantasticFiasco/logo/master/logo.ansi)"
    - run: yarn install --immutable --immutable-cache
    - run: yarn build
    - run: yarn test
    - run: yarn lint
    - run: if [ ${{ matrix.node-version }} == 16.x ]; then node ../../scripts/publish-on-tag.js; fi
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
