name: axis-configuration

on:
  push:
    branches:
      - "**"
    paths:
      - .github/workflows/axis-configuration.yml
      - packages/axis-configuration/**
    tags:
      - axis-configuration@**
  workflow_dispatch:

defaults:
  run:
    working-directory: packages/axis-configuration

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v5
      with:
        node-version: lts/*
        check-latest: true
    - run: yarn install --immutable --immutable-cache
    - run: yarn build
    - run: yarn test
    - run: ESLINT_USE_FLAT_CONFIG=false yarn lint
    - name: Publish on tag
      run: |
        cd ../..
        yarn install --immutable --immutable-cache
        node ./scripts/publish-on-tag.js
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
