name: axis-discovery-bonjour

on:
  push:
    branches:
      - "**"
    paths:
      - .github/workflows/axis-discovery-bonjour.yml
      - packages/axis-discovery-bonjour/**
    tags:
      - axis-discovery-bonjour@**
  workflow_dispatch:

defaults:
  run:
    working-directory: packages/axis-discovery-bonjour

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 17.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: true
    - run: echo -e "$(curl --silent https://raw.githubusercontent.com/FantasticFiasco/logo/master/logo.ansi)"
    - run: yarn install --immutable --immutable-cache
    - run: yarn build
    - run: yarn test
    - run: yarn lint
    - run: |
        if [ ${{ matrix.node-version }} == 16.x ]; then
          pushd ../..
          yarn install --immutable --immutable-cache
          node ./scripts/publish-on-tag.js
          popd
        fi
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
